# https://github.com/tsonglew/dutis/blob/master/config/groups.yaml
groups:
  video:
    - mp4
    - avi
    - mkv
    - mov
    - wmv
    - flv
    - webm
    - m4v
    - mpeg
    - mpg
  audio:
    - mp3
    - wav
    - aac
    - ogg
    - m4a
    - flac
    - wma
    - aiff
  image:
    - jpg
    - jpeg
    - png
    - gif
    - svg
    - webp
    - tiff
    - ico
  code:
    - py
    - js
    - go
    - rs
    - c
    - cpp
    - h
    - hpp
    - java
    - swift
    - rb
    - php
    - ts
    - cs
    - dart
    - lua
    - r
    - pl
    - pm
    - t
    - psgi
    - vb
    - fs
    - fsx
    - fsscript
    - fsi
    - rs
  text:
    - txt
    - md
    - mdc
    - yaml
    - yml
    - xml
    - json
    - toml
    - log
  browser:
    - html
  archive:
    - zip
    - tar
    - gz
    - 7z
    - rar
    - bz2
    - xz
    - iso
