[tools]
### Languages
go = "latest"
node = "lts"
deno = "latest"
rust = "latest"
dotnet = "8"
python = ['latest', '3.10', '3.8']
ruby = "latest"
java = "openjdk-21"

aqua = "latest"
ubi = "latest"

"go:github.com/cweill/gotests/gotests" = "latest"

"npm:@trunkio/launcher" = "latest"

golangci-lint = "latest"
"npm:pnpm" = "latest"
"npm:prettier" = "latest"

### python tools
uv = "latest"
"pipx:ruff" = "latest"
"pipx:bandit" = "latest"
"pipx:poetry" = "latest"

### cloud tools
aws-cli = "latest"
aws-sam-cli = "latest"
"pipx:aws-sam-cli" = "latest"
"pipx:awsume" = { version = "latest", uvx_args = "--with awsume-1password-plugin --with awsume-console-plugin" }
"pipx:aws-sso-util" = "latest"
azure = "latest"
gcloud = "latest"
firebase = "latest"

"gem:cfn-nag" = "latest"
"pipx:cfn-lint" = "latest"
"pipx:sceptre" = "latest"

terraform = "latest"
terragrunt = "latest"
terramate = "latest"
terraform-docs = "latest"
terraformer = "latest"
tflint = "latest"
tfsec = "latest"

pulumi = "latest"

# Database tools
"sqlite" = "latest"
"pipx:pgcli" = { version = "latest", uvx_args = "--with psycopg_binary" }
"pipx:mycli" = "latest"
"pipx:litecli" = "latest"
"pipx:iredis" = "latest"
usql = "latest"
psqldef = "latest"
mssqldef = "latest"
"pipx:pg_activity" = { version = "latest", extras = "psycopg" }
"pipx:sqruff" = "latest"
duckdb = "latest"

"ubi:jqlang/jq" = "latest"
"biome" = "latest"

"go:github.com/minio/mc" = "latest"

### Github tools
github-cli = "latest"
ghq = "latest"
actionlint = "latest"
"npm:git-trim" = "latest"

### api tools
"npm:@typespec/compiler" = "latest"

"ubi:hadolint/hadolint" = "latest"

ollama = "latest"
"pipx:kaggle" = "latest"

android-sdk = "latest"

"aqua:BurntSushi/ripgrep" = "latest"
act = "latest"
usage = "latest"
task = "latest"
vim = "latest"
dasel = "latest"
difftastic = "latest"
"go:github.com/dependabot/cli/cmd/dependabot" = "latest"
"npm:jsonata" = "latest"
"pipx:httpie" = "latest"
yq = "latest"
"ubi:cantino/mcfly" = "latest"
"go:github.com/f/mcptools/cmd/mcptools" = "latest"
go-jsonnet = "latest"
"npm:cspell" = "latest"
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
pre-commit = "latest"
checkmake = "latest"
1password = "latest"
delta = "latest"
"asdf:jimmidyson/asdf-upx" = "latest"
"pipx:tldr" = "latest"
zoxide = "latest"
fzf = "latest"
"aqua:slack.com/slack-cli" = "latest"
fd = "latest"
"npm:@sourcegraph/cody" = "latest"
"npm:@openai/codex" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:zx" = "latest"
# "pipx:openai-whisper" = "latest"
"npm:@google/gemini-cli" = "latest"
"pipx:deepdiff" = { version = "latest", extras = "cli" }
maven = "3"
"pipx:vcstool" = "latest"
"ubi:tsonglew/dutis" = "latest"
"npm:ccusage" = "latest"
"pipx:ultralytics" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
