[tools]
go = "latest"
node = "lts"
deno = "latest"
rust = "latest"
dotnet = "8"
python = "latest"   # for other tools
ruby = "latest"
java = "openjdk-21"

aqua = "latest"

golangci-lint = "latest"

biome = "latest"
"npm:pnpm" = "latest"
"npm:prettier" = "latest"

uv = "latest"
"pipx:ruff" = "latest"
"pipx:bandit" = "latest"
"pipx:poetry" = "latest"

aws-cli = "latest"
"pipx:aws-sam-cli" = "latest"
"pipx:awsume" = { version = "latest", uvx_args = "--with awsume-1password-plugin --with awsume-console-plugin" }
"pipx:aws-sso-util" = "latest"
azure = "latest"
gcloud = "latest"
firebase = "latest"

"gem:cfn-nag" = "latest"
"pipx:cfn-lint" = "latest"
"pipx:sceptre" = "latest"

terraform = "latest"
terragrunt = "latest"
terramate = "latest"
terraform-docs = "latest"
terraformer = "latest"
tflint = "latest"
tfsec = "latest"

pulumi = "latest"

"sqlite" = "latest"
"pipx:pgcli" = "latest"
"pipx:mycli" = "latest"
"pipx:litecli" = "latest"
"pipx:iredis" = "latest"
usql = "latest"
psqldef = "latest"
mssqldef = "latest"
"pipx:sqruff" = "latest"
duckdb = "latest"

github-cli = "latest"
ghq = "latest"
actionlint = "latest"

hadolint = "latest"

ollama = "latest"

android-sdk = "latest"

peco = "latest"
just = "latest"
vim = "latest"
dasel = "latest"
"npm:git-trim" = "latest"
"npm:jsonata" = "latest"
"pipx:httpie" = "latest"
yq = "latest"
"ubi:jqlang/jq" = "latest"
go-jsonnet = "latest"
"npm:cspell" = "latest"
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
pre-commit = "latest"
checkmake = "latest"
1password = "latest"
delta = "latest"
"asdf:jimmidyson/asdf-upx" = "latest"
"pipx:tldr" = "latest"
zoxide = "latest"
fzf = "latest"
"aqua:slack.com/slack-cli" = "latest"
fd = "latest"

[settings]
experimental = true
