# common
brew "make"
brew "git"
brew "gnu-sed"
brew "grep"
brew "wget"
brew "telnet"
brew "tree"
brew "tmux"
brew "git-trim"

brew "libyaml" # for ruby

# sh
brew "zsh"
brew "zsh-completions"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
# brew "zsh-fast-syntax-highlighting"
# TODO
# brew "zsh-history-substring-search"
brew "starship"
cask "font-hack-nerd-font"

# infra
# brew "tfnotify"
# brew "tfrun"
